# We need a decent ubuntu dist
# Based on https://github.com/felixduvallet/ros-travis-integration

sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language:
  - generic
cache:
  - apt
env:
       global:

                - ROS_CI_DESKTOP="$(lsb_release -cs)"
                - CI_SOURCE_PATH=$(pwd)
                - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
                - ROS_PARALLEL_JOBS='-j8 -l6'

matrix:
                - ROS_DISTRO=kinetic
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
#            - kalakris-cmake
#            - boost-latest
#            - kubuntu-backports
#            - ubuntu-toolchain-r-test
#            - george-edison55-precise-backports
#            - sourceline: 'ppa:v-launchpad-jochen-sprickerhof-de/pcl'
          packages:
#            - g++-5
#            - cmake
#            - cmake-data
#            - libpcl-1.7-all-dev
#           - libgtest-dev

before_install:
  - pip install --user cpp-coveralls
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  #- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
 #apt-get clean
 #rm -rf /var/lib/apt/lists/*
 #apt-get clean
 #apt-get update 
 #apt-get upgrade
  - sudo apt-get update -qq
  - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-pcl
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep to install dependencies.
  - sudo rosdep init
  - rosdep update
install:
  - sudo apt-get install -y -qq lcov
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  # Create the devel/setup.bash (run catkin_make with an empty workspace) and
  # source it to set the path variables.
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash
  # Add the package under integration to the workspace using a symlink.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .
script:
  #- export CXX=$COMPILER;
  #- mkdir build
  #- cd build
  #- cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Release ../
  #- make
  #- make code_coverage
  #- test/cpp-test

  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  #- catkin_make $( [ -f $CATKIN_OPTIONS ] && cat $CATKIN_OPTIONS ) -DCMAKE_BUILD_TYPE=Release
  - catkin_make -DCMAKE_BUILD_TYPE=Release

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
